# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#home
    weight: 10
  - name: Über mich
    url: /#about
    weight: 20
  - name: Coaching
    url: /#coaching
    identifier: coaching
    weight: 30
  - name: Coaching
    url: /#coaching
    parent: coaching
    weight: 30
  - name: Personal Coaching
    url: /#pcoaching
    parent: coaching
    weight: 31
  - name: Business Coaching
    url: /#bcoaching
    parent: coaching
    weight: 32
  - name: Bewegung
    url: /#bewegung
    weight: 40
  - name: Netzwerk
    url: /#netzwerk
    weight: 50
  - name: Kontakt
    url: /#kontakt
    weight: 60
